architecture: replication
auth:
  enabled: true
  existingSecret: interview-redis-auth
master:
  persistence:
    enabled: true
    size: 8Gi
  podDisruptionBudget:
    create: true
replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 8Gi
  podDisruptionBudget:
    create: true
sentinel:
  enabled: true
  quorum: 2
metrics:
  enabled: true
